source 'https://rubygems.org'

ruby '2.2.3'

gem 'rails'
gem 'sass-rails'
gem 'coffee-rails'
gem 'bootstrap-on-rails'
gem 'less-rails'
gem 'therubyracer', platforms: :ruby

gem 'thin'
gem 'jquery-rails'
gem 'pry', group: [:development, :test]

gem 'typhoeus'
gem 'virtus'
gem 'addressable'
gem 'hashie'
