source 'https://rubygems.org'

ruby '2.2.3'

gem 'rails'
gem 'responders', '~> 2.0'

gem 'sqlite3'
gem 'bcrypt-ruby'
gem 'thin'
gem 'active_model_serializers'
gem 'pry', group: [:development, :test]
gem 'faker'
